### ISSUE TITLE
Getting `Bad handler node_modules/@iopipe/iopipe/handler` on example SLS hello world

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-cli#10]
When deploying the HelloWorld template using SLS Framework and installing using the CLI, I get the following error when invoking the function:

`"errorMessage": "Bad handler node_modules/@iopipe/iopipe/handler"`

Steps to reproduce:
`serverless create --template hello-world`
`serverless deploy`
`sls invoke -f helloWorld` --> It should work
`iopipe lambda install -f serverless-hello-world-dev-helloWorld -r us-east-1 -t TOKEN`  --> `Install complete.`
`sls invoke -f helloWorld` --> Error

**Comment by ewindisch** [comment]
Marking as wontfix as we will move to using a custom provider. Node support has been removed temporarily
